//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTX.DesignPatterns.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatternName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatternName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTX.DesignPatterns.Properties.PatternName", typeof(PatternName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract factory.
        /// </summary>
        internal static string AbstractFactoryName {
            get {
                return ResourceManager.GetString("AbstractFactoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapter.
        /// </summary>
        internal static string AdapterName {
            get {
                return ResourceManager.GetString("AdapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        internal static string BridgeName {
            get {
                return ResourceManager.GetString("BridgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder.
        /// </summary>
        internal static string BuilderName {
            get {
                return ResourceManager.GetString("BuilderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain of responsibility.
        /// </summary>
        internal static string ChainOfResponsibilityName {
            get {
                return ResourceManager.GetString("ChainOfResponsibilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string CommandName {
            get {
                return ResourceManager.GetString("CommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite.
        /// </summary>
        internal static string CompositeName {
            get {
                return ResourceManager.GetString("CompositeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator.
        /// </summary>
        internal static string DecoratorName {
            get {
                return ResourceManager.GetString("DecoratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facade.
        /// </summary>
        internal static string FacadeName {
            get {
                return ResourceManager.GetString("FacadeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory method.
        /// </summary>
        internal static string FactoryMethodName {
            get {
                return ResourceManager.GetString("FactoryMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyweight.
        /// </summary>
        internal static string FlyweightName {
            get {
                return ResourceManager.GetString("FlyweightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreter.
        /// </summary>
        internal static string InterpreterName {
            get {
                return ResourceManager.GetString("InterpreterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterator.
        /// </summary>
        internal static string IteratorName {
            get {
                return ResourceManager.GetString("IteratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediator.
        /// </summary>
        internal static string MediatorName {
            get {
                return ResourceManager.GetString("MediatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memento.
        /// </summary>
        internal static string MementoName {
            get {
                return ResourceManager.GetString("MementoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer.
        /// </summary>
        internal static string ObserverName {
            get {
                return ResourceManager.GetString("ObserverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prototype.
        /// </summary>
        internal static string PrototypeName {
            get {
                return ResourceManager.GetString("PrototypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string ProxyName {
            get {
                return ResourceManager.GetString("ProxyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton.
        /// </summary>
        internal static string SingletonName {
            get {
                return ResourceManager.GetString("SingletonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        internal static string StrategyName {
            get {
                return ResourceManager.GetString("StrategyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template method.
        /// </summary>
        internal static string TemplateMethodName {
            get {
                return ResourceManager.GetString("TemplateMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor.
        /// </summary>
        internal static string VisitorName {
            get {
                return ResourceManager.GetString("VisitorName", resourceCulture);
            }
        }
    }
}
