//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTX.DesignPatterns.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatternDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatternDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DTX.DesignPatterns.Properties.PatternDescription", typeof(PatternDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides an interface for creating families of related or dependent objects without specifying their concrete class..
        /// </summary>
        internal static string AbstractFactoryDescription {
            get {
                return ResourceManager.GetString("AbstractFactoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert the interface of a class into another interface clients expect. Lets classes work together that couldn&apos;t otherwise because of incompatible interfaces.
        ///.
        /// </summary>
        internal static string AdapterDescription {
            get {
                return ResourceManager.GetString("AdapterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decouple an abstraction from its implementation so that the two can vary independently.
        ///.
        /// </summary>
        internal static string BridgeDescription {
            get {
                return ResourceManager.GetString("BridgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate the construction of a complex object from its representing so that the same construction process can create different representations..
        /// </summary>
        internal static string BuilderDescription {
            get {
                return ResourceManager.GetString("BuilderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid coupling the sender of a request to its receiver by giving more than one object a chance to handle the request. Chain the receiving objects and pass the request along the chain until an object handles it.
        ///.
        /// </summary>
        internal static string ChainOfResponsibilityDescription {
            get {
                return ResourceManager.GetString("ChainOfResponsibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encapsulate a request as an object, thereby letting you parameterize clients with different requests, queue or log requests, and support undoable operations..
        /// </summary>
        internal static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose objects into tree structures to represent part-whole hierarchies. Lets clients treat individual objects and compositions of objects uniformly.
        ///.
        /// </summary>
        internal static string CompositeDescription {
            get {
                return ResourceManager.GetString("CompositeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach additional responsibilities to an object dynamically. Provide a flexible alternative to sub-classing for extending functionality.
        ///.
        /// </summary>
        internal static string DecoratorDescription {
            get {
                return ResourceManager.GetString("DecoratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a unified interface to a set of interfaces in a subsystem. Defines a high level interface that makes the subsystem easier to use..
        /// </summary>
        internal static string FacadeDescription {
            get {
                return ResourceManager.GetString("FacadeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define an interface for creating an object, but let subclasses decide which class to instantiate. Lets a class defer instantiation to subclasses..
        /// </summary>
        internal static string FactoryMethodDescription {
            get {
                return ResourceManager.GetString("FactoryMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use sharing to support large numbers of fine grained objects efficiently..
        /// </summary>
        internal static string FlyweightDescription {
            get {
                return ResourceManager.GetString("FlyweightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given a language, define a representation for its grammar along with an interpreter that uses the representation to interpret sentences in the language.
        ///.
        /// </summary>
        internal static string InterpreterDescription {
            get {
                return ResourceManager.GetString("InterpreterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given a language, define a representation for its grammar along with an interpreter that uses the representation to interpret sentences in the language..
        /// </summary>
        internal static string IteratorDescription {
            get {
                return ResourceManager.GetString("IteratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define an object that encapsulates how a set of objects interact. Promotes loose coupling by keeping objects from referring to each other explicitly and it lets you vary their interactions independently.
        ///.
        /// </summary>
        internal static string MediatorDescription {
            get {
                return ResourceManager.GetString("MediatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without violating encapsulation, capture and externalize an object&apos;s internal state so that the object can be restored to this state later.
        ///.
        /// </summary>
        internal static string MementoDescription {
            get {
                return ResourceManager.GetString("MementoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a one-to-many dependency between objects so that when one object changes state, all its dependents are notified and updated automatically.
        ///.
        /// </summary>
        internal static string ObserverDescripton {
            get {
                return ResourceManager.GetString("ObserverDescripton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the kinds of objects to create using a prototypical instance, and create new objects by copying this prototype..
        /// </summary>
        internal static string PrototypeDescription {
            get {
                return ResourceManager.GetString("PrototypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a surrogate or placeholder for another object to control access to it..
        /// </summary>
        internal static string ProxyDescription {
            get {
                return ResourceManager.GetString("ProxyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure a class only has one instance and provide a global point of access to it..
        /// </summary>
        internal static string SingletonDescription {
            get {
                return ResourceManager.GetString("SingletonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow an object to alter its behavior when its internal state changes. The object will appear to change its class.
        ///.
        /// </summary>
        internal static string StateDescription {
            get {
                return ResourceManager.GetString("StateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a family of algorithms, encapsulate each one, and make them interchangeable. Lets the algorithm vary independently from clients that use it.
        ///.
        /// </summary>
        internal static string StrategyDescription {
            get {
                return ResourceManager.GetString("StrategyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the skeleton of an algorithm in an operation, deferring some steps to subclasses. Lets subclasses redefine certain steps of an algorithm without changing the algorithm&apos;s structure.
        ///.
        /// </summary>
        internal static string TemplateMethodDescription {
            get {
                return ResourceManager.GetString("TemplateMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represent an operation to be performed on the elements of an object structure. Lets you define a new operation without changing the classes of the elements on which it operates.
        ///.
        /// </summary>
        internal static string VisitorDescription {
            get {
                return ResourceManager.GetString("VisitorDescription", resourceCulture);
            }
        }
    }
}
